<?php
$blockObj= $block->getLayout()->createBlock('Ws\Customer\Block\Customergroups');
$customer = $blockObj->getCustomerData();
$wsPec = $customer->getCustomAttribute('ws_destcode')->getValue() ?? '';
?>
<fieldset class="fieldset info">
<div class="field pec">
    <label class="label" for="destcode"><span><?php echo $block->escapeHtml(__('Codice Destinatario')) ?></span></label>
    <div class="control">
        <input type="text" name="ws_destcode" value="<?php echo $wsPec ?>" title="<?php echo __('Codice Destinatario') ?>" class="input-text " id="ws_destcode">
    </div>
</div>
</fieldset>