<?php
$blockObj= $block->getLayout()->createBlock('Ws\Customer\Block\Customergroups');
$customer = $blockObj->getCustomerData();
$wsPec = $customer->getCustomAttribute('ws_pec')->getValue() ?? '';
?>
<fieldset class="fieldset info">
<div class="field pec">
    <label class="label" for="pec"><span><?php echo $block->escapeHtml(__('PEC')) ?></span></label>
    <div class="control">
        <input type="text" name="ws_pec" value="<?php echo $wsPec ?>" title="<?php echo __('PEC') ?>" class="input-text " id="ws_pec">
    </div>
</div>
</fieldset>